import type { FacebookPolicyRule } from './facebook-policy.types';
import { FACEBOOK_ADS_POLICY_CATALOG } from './facebook-policy.config';

const code = (group: keyof typeof FACEBOOK_ADS_POLICY_CATALOG) =>
  FACEBOOK_ADS_POLICY_CATALOG[group]!.policyCode;

/** Every rule requires ≥2 matched signals (no single-keyword conclusions). */
export const FACEBOOK_POLICY_RULES: FacebookPolicyRule[] = [
  {
    id: 'absolute-guarantees',
    policyGroup: 'ABSOLUTE_CLAIMS',
    policyCode: code('ABSOLUTE_CLAIMS'),
    severity: 'HIGH',
    minSignals: 2,
    signals: [
      'cam kết',
      'cam ket',
      '100%',
      '100 %',
      'chữa khỏi',
      'chua khoi',
      'khỏi hẳn',
      'khỏi hoàn toàn',
      'đảm bảo khỏi',
      'triệt để',
      'triet de',
      'hết sạch',
      'hết hẳn',
    ],
    reason: 'Cam kết tuyệt đối / đảm bảo kết quả y khoa — dễ vi phạm Meta Ads (misleading claims).',
    remediation:
      'Đổi sang ngôn ngữ hỗ trợ/cải thiện, thêm disclaimer tùy cơ địa, bỏ “100%/chữa khỏi”.',
    suggestedReplacement: 'hỗ trợ cải thiện theo cơ địa',
  },
  {
    id: 'health-treatment-claims',
    policyGroup: 'HEALTH',
    policyCode: code('HEALTH'),
    severity: 'HIGH',
    minSignals: 2,
    signals: [
      'điều trị',
      'dieu tri',
      'chữa',
      'bệnh',
      'nám',
      'nam',
      'ung thư',
      'tiểu đường',
      'huyết áp',
      'giảm cân',
      'giam can',
      'triệt lông vĩnh viễn',
      'y khoa',
      'bác sĩ kê',
    ],
    reason:
      'Khẳng định điều trị / kết quả sức khỏe nhạy cảm — cần thận trọng với chính sách Health.',
    remediation: 'Tránh từ “điều trị/chữa bệnh”; nói trải nghiệm chăm sóc, thêm disclaimer.',
    suggestedReplacement: 'hỗ trợ chăm sóc / cải thiện vẻ ngoài (tùy cơ địa)',
  },
  {
    id: 'before-after-transformation',
    policyGroup: 'BEFORE_AFTER',
    policyCode: code('BEFORE_AFTER'),
    severity: 'MEDIUM',
    minSignals: 2,
    signals: [
      'trước-sau',
      'truoc-sau',
      'trước sau',
      'before after',
      'before/after',
      'chỉ sau',
      'sau 7 ngày',
      'sau 3 ngày',
      'thần kỳ',
      'lột xác',
      'đổi đời',
    ],
    reason: 'Gợi ý biến đổi trước/sau hoặc kết quả nhanh — dễ bị coi là gây hiểu nhầm.',
    remediation: 'Bỏ trước-sau / mốc thời gian tuyệt đối; dùng case có disclaimer.',
    suggestedReplacement: 'kết quả có thể khác nhau tùy cơ địa',
  },
  {
    id: 'personal-attributes',
    policyGroup: 'PERSONAL_ATTRIBUTES',
    policyCode: code('PERSONAL_ATTRIBUTES'),
    severity: 'HIGH',
    minSignals: 2,
    signals: [
      'bạn đang bị',
      'ban dang bi',
      'bạn bị',
      'vì bạn',
      'do bạn',
      'người béo',
      'người xấu',
      'da đen',
      'già nua',
      'tự ti vì',
      'xấu xí',
    ],
    reason: 'Gọi tên thuộc tính cá nhân tiêu cực của người xem — vi phạm Personal Attributes.',
    remediation: 'Nói vấn đề chung / sản phẩm, không chỉ thẳng “bạn đang bị…”.',
    suggestedReplacement: 'nhiều khách quan tâm đến…',
  },
  {
    id: 'financial-misleading',
    policyGroup: 'FINANCIAL',
    policyCode: code('FINANCIAL'),
    severity: 'HIGH',
    minSignals: 2,
    signals: [
      'kiếm tiền',
      'thu nhập thụ động',
      'giàu nhanh',
      'lãi suất',
      'vay tiền',
      'tín dụng',
      'otp ngân hàng',
      'paypal',
      'chuyển khoản xác minh',
      'đầu tư chắc thắng',
    ],
    reason: 'Nội dung tài chính / thu nhập dễ gây hiểu nhầm hoặc lừa đảo.',
    remediation: 'Bỏ cam kết thu nhập/vay; không yêu cầu OTP/PayPal trên landing ads.',
  },
  {
    id: 'sensational-clickbait',
    policyGroup: 'SENSATIONAL',
    policyCode: code('SENSATIONAL'),
    severity: 'MEDIUM',
    minSignals: 2,
    signals: [
      'sốc',
      'không thể tin',
      'bí mật ngành',
      'bác sĩ giấu',
      'cảnh báo đỏ',
      'phát hiện kinh hoàng',
      'click ngay kẻo muộn',
      'chỉ còn hôm nay!!!',
    ],
    reason: 'Giật gân / clickbait — giảm chất lượng quảng cáo và dễ bị hạn chế phân phối.',
    remediation: 'Viết lợi ích rõ, bỏ câu sốc và dấu !!!.',
  },
  {
    id: 'prohibited-content',
    policyGroup: 'PROHIBITED',
    policyCode: code('PROHIBITED'),
    severity: 'CRITICAL',
    minSignals: 2,
    signals: [
      'súng',
      'ma túy',
      'cần sa',
      'vũ khí',
      'buôn người',
      'nội dung khiêu dâm',
      'sex toy trẻ em',
      'hack tài khoản',
      'phần mềm crack',
    ],
    reason: 'Nội dung có dấu hiệu thuộc nhóm bị cấm trên Meta.',
    remediation: 'Loại bỏ hoàn toàn; không chạy ads với nội dung này.',
  },
  {
    id: 'special-ad-housing-jobs-credit',
    policyGroup: 'SPECIAL_AD_CATEGORY',
    policyCode: code('SPECIAL_AD_CATEGORY'),
    severity: 'HIGH',
    minSignals: 2,
    signals: [
      'cho thuê nhà',
      'bán căn hộ',
      'mua nhà',
      'bất động sản',
      'tuyển dụng',
      'tuyển nhân viên',
      'mức lương',
      'vay tín dụng',
      'thẻ tín dụng',
      'khoản vay',
      'bảo hiểm nhân thọ chính trị',
    ],
    reason:
      'Nội dung nhà ở / việc làm / tín dụng thường thuộc Special Ad Categories — cần khai báo đúng.',
    remediation: 'Chọn đúng Special Ad Category (HOUSING / EMPLOYMENT / CREDIT) hoặc chỉnh copy.',
  },
];
