import { Global, Module } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { Queue } from 'bullmq';
import { QUEUE_NAMES } from '@marketingspa/shared';
import {
  AUTOMATION_MESSAGE_QUEUE,
  APPOINTMENT_REMINDER_QUEUE,
  AUTO_POST_QUEUE,
  BACKUP_QUEUE,
  CAMPAIGN_QUEUE,
  DAILY_REPORT_QUEUE,
  HRM_ATTENDANCE_REBUILD_QUEUE,
  LEAD_ALERT_QUEUE,
  OFFLINE_CONVERSION_QUEUE,
  MESSAGING_WEBHOOK_QUEUE,
  MESSAGING_CAMPAIGN_PLAN_QUEUE,
  MESSAGING_CAMPAIGN_DISPATCH_QUEUE,
  MESSAGING_SEND_QUEUE,
  ADS_SYNC_QUEUE,
  ADS_ACTION_QUEUE,
  AFFILIATE_HOLD_QUEUE,
  VIDEO_TRANSCRIPTION_QUEUE,
  AD_URL_ANALYZE_QUEUE,
  MARKETING_AUTOPILOT_OUTCOME_EVAL_QUEUE,
  MARKETING_AUTOPILOT_MISSION_QUEUE,
} from './queue.constants';

function createQueueProvider(token: string, queueName: string) {
  return {
    provide: token,
    inject: [ConfigService],
    useFactory: (config: ConfigService) => {
      const prefix = config.get<string>('QUEUE_PREFIX', 'marketingspa');
      const redisUrl = config.get<string>('REDIS_URL', 'redis://localhost:6379');
      return new Queue(queueName, {
        connection: { url: redisUrl, maxRetriesPerRequest: null },
        prefix,
      });
    },
  };
}

@Global()
@Module({
  providers: [
    createQueueProvider(CAMPAIGN_QUEUE, QUEUE_NAMES.CAMPAIGN_SEND),
    createQueueProvider(LEAD_ALERT_QUEUE, QUEUE_NAMES.LEAD_ALERT),
    createQueueProvider(APPOINTMENT_REMINDER_QUEUE, QUEUE_NAMES.APPOINTMENT_REMINDER),
    createQueueProvider(AUTOMATION_MESSAGE_QUEUE, QUEUE_NAMES.AUTOMATION_MESSAGE),
    createQueueProvider(DAILY_REPORT_QUEUE, QUEUE_NAMES.DAILY_REPORT),
    createQueueProvider(BACKUP_QUEUE, QUEUE_NAMES.BACKUP),
    createQueueProvider(AUTO_POST_QUEUE, QUEUE_NAMES.AUTO_POST_PUBLISH),
    createQueueProvider(HRM_ATTENDANCE_REBUILD_QUEUE, QUEUE_NAMES.HRM_ATTENDANCE_REBUILD),
    createQueueProvider(OFFLINE_CONVERSION_QUEUE, QUEUE_NAMES.OFFLINE_CONVERSION),
    createQueueProvider(MESSAGING_WEBHOOK_QUEUE, QUEUE_NAMES.MESSAGING_WEBHOOK),
    createQueueProvider(MESSAGING_CAMPAIGN_PLAN_QUEUE, QUEUE_NAMES.MESSAGING_CAMPAIGN_PLAN),
    createQueueProvider(
      MESSAGING_CAMPAIGN_DISPATCH_QUEUE,
      QUEUE_NAMES.MESSAGING_CAMPAIGN_DISPATCH,
    ),
    createQueueProvider(MESSAGING_SEND_QUEUE, QUEUE_NAMES.MESSAGING_SEND),
    createQueueProvider(ADS_SYNC_QUEUE, QUEUE_NAMES.ADS_SYNC),
    createQueueProvider(ADS_ACTION_QUEUE, QUEUE_NAMES.ADS_ACTION),
    createQueueProvider(AFFILIATE_HOLD_QUEUE, QUEUE_NAMES.AFFILIATE_HOLD),
    createQueueProvider(VIDEO_TRANSCRIPTION_QUEUE, QUEUE_NAMES.VIDEO_TRANSCRIPTION),
    createQueueProvider(AD_URL_ANALYZE_QUEUE, QUEUE_NAMES.AD_URL_ANALYZE),
    createQueueProvider(
      MARKETING_AUTOPILOT_OUTCOME_EVAL_QUEUE,
      QUEUE_NAMES.MARKETING_AUTOPILOT_OUTCOME_EVAL,
    ),
    createQueueProvider(
      MARKETING_AUTOPILOT_MISSION_QUEUE,
      QUEUE_NAMES.MARKETING_AUTOPILOT_MISSION,
    ),
  ],
  exports: [
    CAMPAIGN_QUEUE,
    LEAD_ALERT_QUEUE,
    APPOINTMENT_REMINDER_QUEUE,
    AUTOMATION_MESSAGE_QUEUE,
    DAILY_REPORT_QUEUE,
    BACKUP_QUEUE,
    AUTO_POST_QUEUE,
    HRM_ATTENDANCE_REBUILD_QUEUE,
    OFFLINE_CONVERSION_QUEUE,
    MESSAGING_WEBHOOK_QUEUE,
    MESSAGING_CAMPAIGN_PLAN_QUEUE,
    MESSAGING_CAMPAIGN_DISPATCH_QUEUE,
    MESSAGING_SEND_QUEUE,
    ADS_SYNC_QUEUE,
    ADS_ACTION_QUEUE,
    AFFILIATE_HOLD_QUEUE,
    VIDEO_TRANSCRIPTION_QUEUE,
    AD_URL_ANALYZE_QUEUE,
    MARKETING_AUTOPILOT_OUTCOME_EVAL_QUEUE,
    MARKETING_AUTOPILOT_MISSION_QUEUE,
  ],
})
export class QueueModule {}
