export const CAMPAIGN_QUEUE = 'CAMPAIGN_QUEUE';
export const LEAD_ALERT_QUEUE = 'LEAD_ALERT_QUEUE';
export const APPOINTMENT_REMINDER_QUEUE = 'APPOINTMENT_REMINDER_QUEUE';
export const AUTOMATION_MESSAGE_QUEUE = 'AUTOMATION_MESSAGE_QUEUE';
export const DAILY_REPORT_QUEUE = 'DAILY_REPORT_QUEUE';
export const BACKUP_QUEUE = 'BACKUP_QUEUE';
