/var/www/marketingaut_usr/data/releases/autopilot-homepage-20260824_192247/apps/logs/*.log {
  daily
  rotate 14
  size 20M
  compress
  delaycompress
  missingok
  notifempty
  copytruncate
  dateext
  su marketingaut_usr marketingaut_usr
}
